8391256: TestZoneTextPrinterParser.java assertion fails with expected: <Mountain Standard Time> but was: <Mountain Daylight Time>
Backport-of: ed1c970702b800347c3459cab62b350eb980cc16
(cherry picked from commit 1fac148c2dcc5c2f065999ff3562a76e3c699d0f)